### PR TITLE
[Feature #157782871] Adds Admin's ability to navigate the app using the navbar

### PR DESCRIPTION
**Pull request by maxwellgithinji**
**What does this PR do?**
Enables the admin to navigate to the New user requests, approved, disapproved and resolved user requests and also the ability to log out of the system. 

**Description of Tasks to be Completed**
_The Admin can:_
* Navigate to the new user requests
* Navigate to the approved user requests
* Navigate to the disapproved user requests
* Navigate to the resolved user requests
* Log out of the system

**How Should This be Manually Tested?**
_After cloning the Repo:_
* Navigate to ```templates/admin_home.html``` file and open it with a browser.
* Click on the New link to navigate to the new user requests.
* Click on the Approved link to navigate to the approved user requests.
* Click on the Disapproved link to navigate to the disapproved user requests.
* Click on the Logout link to navigate to log out of the system.

**Any background context you want to provide?**
The navigation to the Profile is not yet implemented

**What are the Relevant Pivotal Tracker stories?**
* https://www.pivotaltracker.com/story/show/157787576
* https://www.pivotaltracker.com/story/show/157787893
* https://www.pivotaltracker.com/story/show/157787979
* https://www.pivotaltracker.com/story/show/157788013
* https://www.pivotaltracker.com/story/show/157782170
* https://www.pivotaltracker.com/story/show/157789508

### CODE REVIEW

**Comment by maxwellgithinji** [comment]
Thanks for the review

**Comment by janetnim** [comment]
Great job...well detailed
maybe include screenshots as well

**Comment by gitaumoses4** [comment]
Well structured and details PR. Good job. 

I would suggest the following.
- Ensure your commit messages are between 50 and 72 characters.
- Use the imperative mood in the commit message.
Your commit message should always complete the following sentence
**If applied, this commit will** _________[commit message here_________

**Comment by maxwellgithinji** [comment]
Thanks all for the reviews. I will implement the feedback.

**Pull request merged**
